### ISSUE TITLE
Visualisation using windows

### ISSUE THREAD

**Issue by rbouckaert** [BEAST2-Dev/bModelTest#2]
Model analyser fails with error pointing to bModelTest0.html file at "index: 7". This may have something to do with newlines?

**Comment by rbouckaert** [comment]
The offending exception:

java.net.URISyntaxException: Illegal character in authority at index 7: file://C:\Users\user\BEAST\2.4\bModelTest\\js/bModelTest0.html
    at java.net.URI$Parser.fail(Unknown Source)
    at java.net.URI$Parser.parseAuthority(Unknown Source)
    at java.net.URI$Parser.parseHierarchical(Unknown Source)
    at java.net.URI$Parser.parse(Unknown Source)
    at java.net.URI.<init>(Unknown Source)
    at beast.app.tools.BModelAnalyser.openUrl(Unknown Source)
    at beast.app.tools.BModelAnalyser.processTrace(Unknown Source)
    at beast.app.tools.BModelAnalyser.run(Unknown Source)
    at beast.app.tools.BModelAnalyser.main(Unknown Source)

**Comment by rbouckaert** [comment]
fixed by 81ce97b6d8214ae1ea738fc44476dd65b44bd17b
